### ISSUE TITLE
Airbrake-django breaks django-sass-processor

### ISSUE THREAD

**Issue by benpetty** [airbrake/airbrake-django#22]
I initially filed an issue on the `django-sass-processor` repo (https://github.com/jrief/django-sass-processor/issues/92) but turns out removing `airbrake-django` fixed the problem. It looks like `airbrake-django` is somehow causing the `./manage.py compilescss` [(source)](https://github.com/jrief/django-sass-processor/blob/master/sass_processor/management/commands/compilescss.py) script to run python2 syntax in the python3 `ast` module. Any idea why? I'd love to use both packages.

```
........................................................................................................................................Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 153, in handle
    self.parse_source(py_source)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 199, in parse_source
    tree = ast.parse(open(filename, 'rb').read())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 5
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by jamezpolley** [comment]
This seems to come from https://github.com/airbrake/airbrake-django/blob/02b0b422c6cdc8d5727bd6ea045bfdc362b380cd/airbrake/decorators.py#L5

Suggested fix would be to update this to "except Exception as e"; this will break compatibility with python 2.5 and earlier, but work in 2.6 and up.

**Comment by phumpal** [comment]
At this point I don't think it makes sense to support < Python 2.7 but we should patch this for Python 2.7 as there are still a few people on this version.

FWIW if you've upgraded to Python 3 please checkout our new Python notifier https://github.com/airbrake/pybrake.
